model:
  base_learning_rate: 4.5e-7
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    ckpt_path: /home/scur0003/fact/extension/uva_fact_ai_group_5/dp_lora/logs/exp0/checkpoints/last.ckpt
    monitor: val/rec_loss
    embed_dim: 3
    lossconfig:
      target: ldm.modules.losses.StandardLoss
      params:
        kl_weight: 1.0
        trainable: false

    dp_config:
      local: true
      enabled: true
      epsilon: 5
      delta: 1.0e-05
      max_grad_norm: 0.0005
      poisson_sampling: true
      max_batch_size: 8

    ddconfig:
      double_z: true
      z_channels: 3
      resolution: 64
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      num_res_blocks: 2
      attn_resolutions:
      - 8
      - 4
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  feature_path: https://drive.google.com/uc?id=1Xv7VNz8P6Znay08VaIWFWgmAoaeqs0oj
  params:
    batch_size: 32
    num_workers: 6
    wrap: false
    train:
      target: ldm.data.celebahq.CelebAHQ
      params:
        split: train
        target_type: class
        class_attrs:
        - Male
        size: 128
    validation:
      target: ldm.data.celebahq.CelebAHQ
      params:
        split: test
        target_type: class
        class_attrs:
        - Male
        size: 128

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: false
  trainer:
    benchmark: true
    max_epochs: 10
    accelerator: gpu